name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: deploy
        env:
          JENKINS_USER_TOKEN: ${{secrets.JENKINS_USER_TOKEN}}
          JENKINS_JOB_TOKEN: ${{secrets.JENKINS_JOB_TOKEN}}
        run: |
          curl --user $JENKINS_USER_TOKEN https://jenkins.abelab.dev/job/daas-deploy/build -d token=$JENKINS_JOB_TOKEN
